### PR TITLE
Reorder export so it matches planemo lint expectations. Remove ftype from test output

### PR DESCRIPTION
**Pull request by fubar2**
My attempt at fixing #27

Changed export order to match planemo's linter based on lib/galaxy/tool_util/linters/xml_order.py
Remove ftype from test output - planemo's linter declares it illegal

Needs more testing!
Generated ToolFactory code now passes tests and planemo lint for a couple of tools I regenerated...

### CODE REVIEW

**Comment by hexylena** [comment]
Sorry for the trouble you had with flake8, I don't like a lot of the changes you were forced to make it seems here. Do you mind if I walk those back and adjust the linting requirements instead? The diff is a bit hard to read because of all the nonsense/noise.

That said, super if it produces something that planemo is happier with.

**Comment by fubar2** [comment]
> Do you mind if I walk those back and adjust the linting requirements instead? The diff is a bit hard to read because of all the nonsense/noise.

Yes, sorry - I ran black frantically trying to shut flake8 down so it turned into a bit of a whitespace mess. My relationship with linters is an unhappy one as you can probably tell. I could try to fix it but I'm likely to make it worse. 
I also added a Stdios section with Stdio as children so the user can potentially add them as they wish - default is to emit a default of fatal if >= 1 - if none have been added.

eeesh. line break before binary operator - I find myself growling quietly as I read :)

```
flake8 galaxyxml --ignore=E2,E3,E4,E5,W3,W505
galaxyxml/tool/__init__.py:146:71: W504 line break after binary operator
galaxyxml/tool/parameters/__init__.py:685:13: W503 line break before binary operator
galaxyxml/tool/parameters/__init__.py:686:13: W503 line break before binary operator
galaxyxml/tool/parameters/__init__.py:745:13: W503 line break before binary operator
galaxyxml/tool/parameters/__init__.py:746:13: W503 line break before binary operator
The command "flake8 galaxyxml --ignore=E2,E3,E4,E5,W3,W505" exited with 1.

```

**Comment by fubar2** [comment]
ok. I did an appropriate penance by redoing and obeisance was offered to flake8 before pressing the button. It looks a little less awful now. That'll (as we say here) learn me.

**Comment by hexylena** [comment]
Ok, I've got a couple commits on top of this, i'll merge this and get those added. Thanks for this contribution!

But mate, next time, don't fight with flake8! don't waste your time like that. Just submit your changes (I've added a makefile which runs black for you), and if flake complains, I can mute or fix it as I feel appropriate.

**Pull request merged**
