### PR TITLE
Add TestOutputCollection so collections can be tested and TestRepeat for repeats.

### PR DESCRIPTION
**Pull request by fubar2**
This PR adds TestOutputCollection and allows the ToolFactory to generate tools with dummy tests for output collections that pass planemo test. Version bumped...

Arguably, needs extension so individual file names expected to be in the collection can be checked - that will require knowledge that we cannot sanely introspect automagically so will need yet more information on the collection tool form section.

Very lightly tested (TM) - just the plotter tool example.

Suggestions appreciated....

TestRepeat added with tests. Also very lightly tested with a real tool.

### CODE REVIEW

**Review by hexylena — APPROVED** [review]
looks fine to me.

**Comment by hexylena** [comment]
@fubar2 can you update the readme / setup.py with the changelog / bump the version?

**Comment by fubar2** [comment]
Ah. Yes - of course - done.

**Comment by fubar2** [comment]
Managed to get the testrepeat branch fixed so have merged it here.
Toofer the price of one (TM)

**Review by hexylena — APPROVED** [review]
fine for me

**Pull request merged**
